
services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5000"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - auth-service
      
  talleres-service:
    build: ./talleres-service
    ports:
      - "5002:5002"
    restart: always
